config/routes.rb
Rails.application.routes.draw do

  get  '/' => 'posts#new', as: "new_post"
  post '/' => 'posts#create', as: "create_post"

  get 'posts' => 'posts#index'

  get 'anon'     => 'posts#anon'
  get 'avatar'   => 'posts#avatar'
  get 'profile'  => 'posts#profile'

  get 'posts-feed' => 'posts#feed'

end

app/models/post.rb
class Post < ActiveRecord::Base

  scope :latest,  -> { order("created_at DESC") }
  scope :anon,    -> { where(anon_tagged: true) }
  scope :avatar,  -> { where(avatar_tagged: true) }
  scope :profile, -> { where(profile_tagged: true) }
  scope :no_tags, -> { where(anon_tagged: false).where(avatar_tagged: false).where(profile_tagged: false) }
  scope :tonight, -> { where(night_posted: Raster::Application::CURRENT_NIGHT) }

  validates_presence_of :message

  after_create :extract_hashed_persons, :assign_night_posted

  def extract_hashed_persons
    ["anon", "avatar", "profile"].each_with_index do |person, index|
      if message.downcase.match(/##{person}/)
        update_attribute("#{person}_tagged".to_sym, true)
      else
        update_attribute("#{person}_tagged".to_sym, false)
      end
    end
  end

  def assign_night_posted
    update_attribute(:night_posted, Raster::Application::CURRENT_NIGHT)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  include ActionView::Helpers::DateHelper

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.tonight.latest
  end

  def anon
    @person = "Anon"
    @posts = (Post.tonight.anon + Post.tonight.no_tags).sort! { |a,b| b.created_at <=> a.created_at }
    render :index
  end

  def avatar
    @person = "Avatar"
    @posts = (Post.tonight.avatar + Post.tonight.no_tags).sort! { |a,b| b.created_at <=> a.created_at }
    render :index
  end

  def profile
    @person = "Profile"
    @posts = (Post.tonight.profile + Post.tonight.no_tags).sort! { |a,b| b.created_at <=> a.created_at }
    render :index
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save

    new
    render :new
  end

  def feed
    last_post_id = params[:last_post_id]

    response = []

    if Post.count > 0

      Post.tonight.where("id > ?", last_post_id).each do |post|
        response << post
      end

    end

    render :json => response
  end

  private

    def post_params
      params.require(:post).permit(:name, :subject, :message)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Raster</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1><%= @person ? @person : "All" %> Posts</h1>

<p><em>Total Posts: <%= @posts.count %></em></p>

<% @posts.each do |post| %>
  <hr>
  <p style="font-size:1em"><em><%= distance_of_time_in_words_to_now(post.created_at) %> ago</em></p>
  <p><%= post.message %></p>
<% end %>
<hr>

app/views/posts/new.html.erb
<div class="main_form">
<h1>What's on your mind?</h1>
<h2>Tag a character using these tags <br><strong>#anon &nbsp; #avatar &nbsp; #profile</strong><br></h2>
<div id="textarea" contenteditable="true" onkeydown="" onkeyup="textAreaAdjust(this); limitChars(this);"></div>
<%= form_for @post, url: create_post_path(@post),method: 'post' do |f| %>
<div id="charsLeft"></div>
  <br>
  <%= f.text_area :message ,style: "display:none", id: "oldTextArea" %>
  <br>

  <%= f.submit "Create", onClick: "getContent()", id: "submit" %>
<% end %>

</div>

<script>
function checkValid(o){
	//highlightTags(o);	
	limitChars(o);
	textAreaAdjust(o);
}
function textAreaAdjust(o) {
    o.style.height = "1px";
    o.style.height = (10+o.scrollHeight)+"px";
}
var characterLimit = 140;
var input = $(".textarea");

function limitChars(who){
    if(who){
        var L = who.innerText.length;
        if(L> characterLimit - 5){
            who.style.color= 'orange';
        }
        else who.style.color= ''
	var text = $(who).text().substring(0,characterLimit);
        if(L >= characterLimit ){
            $(who).focus().text("").text(text);    //innerText= who.innerText.substring(0, characterLimit);
            who.style.color= 'red';
        }
	$("#charsLeft").text(characterLimit - text.length);
    }
}
function getContent(){
	document.getElementById('oldTextArea').value = document.getElementById('textarea').innerText;
}
</script>